---
title: "Binomial Exact Confidence Intervals"
output: 
  flexdashboard::flex_dashboard:
    orientation: columns
    vertical_layout: fill
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(shiny)
library(tidyverse)
library(ggplot2)
```


Inputs {.sidebar}
-----------------------------------------------------------------------


```{r}
numericInput("successes", h3("Successes:"), value =0,  min = 0)

numericInput("trials", h3("Trials:"),value =1,  min = 1)

actionButton("submit", label="Submit")



ci = function(x, n, a){
  lo = (1 + (n - x + 1)/(x * qf(a/2, 2*x, 2*(n-x+1))))^-1
  hi = (1 + (n - x)/((x+1) * qf(1-a/2, 2*(x+1), 2*(n-x))))^-1
  return(c(lo, hi))
}

ci99 <- eventReactive(input$submit, {ci(input$successes, input$trials, .01)})
ci95 <- eventReactive(input$submit, {ci(input$successes, input$trials, .05)})
ci90 <- eventReactive(input$submit, {ci(input$successes, input$trials, .1)})

```

Results {data-width=350}
-----------------------------------------------------------------------

### Clopper-Pearson (exact) Confidence Interval


```{r}
renderUI({
   HTML(paste('99% confidence interval: ', signif(ci99()[1], 3), '<= p <=', signif(ci99()[2], 3), "<br/>", '95% confidence interval: ', signif(ci95()[1], 3), '<= p <=', signif(ci95()[2], 3), "<br/>", '90% confidence interval: ', signif(ci90()[1], 3), '<= p <=', signif(ci90()[2], 3)))
  })

```

